# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import machine_pb2 as machine__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in machine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MachineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMachineById = channel.unary_unary(
                '/machine.MachineService/GetMachineById',
                request_serializer=machine__pb2.MachineIdRequest.SerializeToString,
                response_deserializer=machine__pb2.Machine.FromString,
                _registered_method=True)
        self.GetMachineByName = channel.unary_unary(
                '/machine.MachineService/GetMachineByName',
                request_serializer=machine__pb2.MachineNameRequest.SerializeToString,
                response_deserializer=machine__pb2.MachineList.FromString,
                _registered_method=True)
        self.GetMachineByCfg = channel.unary_unary(
                '/machine.MachineService/GetMachineByCfg',
                request_serializer=machine__pb2.MachineCfgRequest.SerializeToString,
                response_deserializer=machine__pb2.MachineList.FromString,
                _registered_method=True)
        self.GetMachineByAdr = channel.unary_unary(
                '/machine.MachineService/GetMachineByAdr',
                request_serializer=machine__pb2.MachineAdrRequest.SerializeToString,
                response_deserializer=machine__pb2.MachineList.FromString,
                _registered_method=True)
        self.GetAllMachines = channel.unary_unary(
                '/machine.MachineService/GetAllMachines',
                request_serializer=machine__pb2.Empty.SerializeToString,
                response_deserializer=machine__pb2.MachineList.FromString,
                _registered_method=True)
        self.UpdateMachine = channel.unary_unary(
                '/machine.MachineService/UpdateMachine',
                request_serializer=machine__pb2.Machine.SerializeToString,
                response_deserializer=machine__pb2.UpdateMachineResponse.FromString,
                _registered_method=True)


class MachineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMachineById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachineByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachineByCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachineByAdr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMachines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMachine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MachineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMachineById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineById,
                    request_deserializer=machine__pb2.MachineIdRequest.FromString,
                    response_serializer=machine__pb2.Machine.SerializeToString,
            ),
            'GetMachineByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineByName,
                    request_deserializer=machine__pb2.MachineNameRequest.FromString,
                    response_serializer=machine__pb2.MachineList.SerializeToString,
            ),
            'GetMachineByCfg': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineByCfg,
                    request_deserializer=machine__pb2.MachineCfgRequest.FromString,
                    response_serializer=machine__pb2.MachineList.SerializeToString,
            ),
            'GetMachineByAdr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineByAdr,
                    request_deserializer=machine__pb2.MachineAdrRequest.FromString,
                    response_serializer=machine__pb2.MachineList.SerializeToString,
            ),
            'GetAllMachines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMachines,
                    request_deserializer=machine__pb2.Empty.FromString,
                    response_serializer=machine__pb2.MachineList.SerializeToString,
            ),
            'UpdateMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMachine,
                    request_deserializer=machine__pb2.Machine.FromString,
                    response_serializer=machine__pb2.UpdateMachineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'machine.MachineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('machine.MachineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MachineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMachineById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/machine.MachineService/GetMachineById',
            machine__pb2.MachineIdRequest.SerializeToString,
            machine__pb2.Machine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMachineByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/machine.MachineService/GetMachineByName',
            machine__pb2.MachineNameRequest.SerializeToString,
            machine__pb2.MachineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMachineByCfg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/machine.MachineService/GetMachineByCfg',
            machine__pb2.MachineCfgRequest.SerializeToString,
            machine__pb2.MachineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMachineByAdr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/machine.MachineService/GetMachineByAdr',
            machine__pb2.MachineAdrRequest.SerializeToString,
            machine__pb2.MachineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllMachines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/machine.MachineService/GetAllMachines',
            machine__pb2.Empty.SerializeToString,
            machine__pb2.MachineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/machine.MachineService/UpdateMachine',
            machine__pb2.Machine.SerializeToString,
            machine__pb2.UpdateMachineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
