# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: machine.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmachine.proto\x12\x07machine\"0\n\x07Machine\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x63\x66g\x18\x03 \x01(\t\"\x1e\n\x10MachineIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x12MachineNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x11MachineCfgRequest\x12\x0b\n\x03\x63\x66g\x18\x01 \x01(\t\" \n\x11MachineAdrRequest\x12\x0b\n\x03\x61\x64r\x18\x01 \x01(\t\"(\n\x15UpdateMachineResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"1\n\x0bMachineList\x12\"\n\x08machines\x18\x01 \x03(\x0b\x32\x10.machine.Machine2\x9b\x03\n\x0eMachineService\x12=\n\x0eGetMachineById\x12\x19.machine.MachineIdRequest\x1a\x10.machine.Machine\x12\x45\n\x10GetMachineByName\x12\x1b.machine.MachineNameRequest\x1a\x14.machine.MachineList\x12\x43\n\x0fGetMachineByCfg\x12\x1a.machine.MachineCfgRequest\x1a\x14.machine.MachineList\x12\x43\n\x0fGetMachineByAdr\x12\x1a.machine.MachineAdrRequest\x1a\x14.machine.MachineList\x12\x36\n\x0eGetAllMachines\x12\x0e.machine.Empty\x1a\x14.machine.MachineList\x12\x41\n\rUpdateMachine\x12\x10.machine.Machine\x1a\x1e.machine.UpdateMachineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'machine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MACHINE']._serialized_start=26
  _globals['_MACHINE']._serialized_end=74
  _globals['_MACHINEIDREQUEST']._serialized_start=76
  _globals['_MACHINEIDREQUEST']._serialized_end=106
  _globals['_MACHINENAMEREQUEST']._serialized_start=108
  _globals['_MACHINENAMEREQUEST']._serialized_end=142
  _globals['_MACHINECFGREQUEST']._serialized_start=144
  _globals['_MACHINECFGREQUEST']._serialized_end=176
  _globals['_MACHINEADRREQUEST']._serialized_start=178
  _globals['_MACHINEADRREQUEST']._serialized_end=210
  _globals['_UPDATEMACHINERESPONSE']._serialized_start=212
  _globals['_UPDATEMACHINERESPONSE']._serialized_end=252
  _globals['_EMPTY']._serialized_start=254
  _globals['_EMPTY']._serialized_end=261
  _globals['_MACHINELIST']._serialized_start=263
  _globals['_MACHINELIST']._serialized_end=312
  _globals['_MACHINESERVICE']._serialized_start=315
  _globals['_MACHINESERVICE']._serialized_end=726
# @@protoc_insertion_point(module_scope)
